import { Noto_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

// Import Noto Sans font
const notoSans = Noto_Sans({
  weight: ['400', '700'], // Set desired font weights
  subsets: ['latin'], // Set the desired subsets
  variable: '--font-noto-sans', // Optional variable name for global usage
});

export const metadata = {
  title: "ParkMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <Toaster position="top-right" reverseOrder={false} /> 
        {children}
      </body>
    </html>
  );
}
